/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/cupy/_environment.py:596: UserWarning: 
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''
Traceback (most recent call last):
  File "/users/hjiang/GenoDistance/code/SampleDisc.py", line 6, in <module>
    from wrapper.wrapper import wrapper
  File "/users/hjiang/GenoDistance/code/wrapper/wrapper.py", line 12, in <module>
    from .rna_wrapper import rna_wrapper
  File "/users/hjiang/GenoDistance/code/wrapper/rna_wrapper.py", line 10, in <module>
    from sample_distance.sample_distance import sample_distance
  File "/users/hjiang/GenoDistance/code/sample_distance/sample_distance.py", line 8, in <module>
    from .EMD import EMD_distances
  File "/users/hjiang/GenoDistance/code/sample_distance/EMD.py", line 8, in <module>
    from pyemd import emd
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pyemd/__init__.py", line 74, in <module>
    from .emd import emd, emd_with_flow, emd_samples
  File "src/pyemd/emd.pyx", line 1, in init pyemd.emd
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
