/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
Traceback (most recent call last):
  File "/users/hjiang/GenoDistance/code/integration_validation.py", line 748, in <module>
    adata_atac, gene_activity, genes_used = atac_integration_validation(
  File "/users/hjiang/GenoDistance/code/integration_validation.py", line 475, in atac_integration_validation
    create_gene_activity_dotplot(gene_activity_subset, available_ordered_genes,
  File "/users/hjiang/GenoDistance/code/integration_validation.py", line 658, in create_gene_activity_dotplot
    pct_pivot = dotplot_df.pivot(index='cell_type', columns='gene', values='pct_expr')
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pandas/core/frame.py", line 9339, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pandas/core/reshape/pivot.py", line 570, in pivot
    result = indexed.unstack(columns_listlike)  # type: ignore[arg-type]
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pandas/core/series.py", line 4615, in unstack
    return unstack(self, level, fill_value, sort)
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 517, in unstack
    unstacker = _Unstacker(
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 154, in __init__
    self._make_selectors()
  File "/users/hjiang/.conda/envs/hongkai/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 210, in _make_selectors
    raise ValueError("Index contains duplicate entries, cannot reshape")
ValueError: Index contains duplicate entries, cannot reshape
